"""initial schema

Revision ID: 62fc571c1e75
Revises: 
Create Date: 2026-06-03 22:00:42.373201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fc571c1e75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_item_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('telegram_msg_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('network_post_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_posts')
    op.drop_table('drafts')
    op.drop_table('raw_items')
    # ### end Alembic commands ###
