"""add tweet_count to published_posts

Revision ID: d20f82f82541
Revises: 62fc571c1e75
Create Date: 2026-06-10 21:06:29.280849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20f82f82541'
down_revision: Union[str, Sequence[str], None] = '62fc571c1e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_posts', sa.Column('tweet_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_posts', 'tweet_count')
    # ### end Alembic commands ###
